### ISSUE TITLE
Create Base Class for Mail Reports in TenantReport

### ISSUE THREAD

**Issue by panjkov** [Microsoft/o365rwsclient#6]
Mail reports cannot inherit TenantReportObject class, as they don't have TenantGuid and TenantName. New base class should be created.

**Comment by panjkov** [comment]
Any updates?

**Comment by julienjtpierre** [comment]
No updates @panjkov sorry. Busy doing other things at the moment. I don't know whether @toneysui has the bandwidth to sort this out?

**Comment by toneysui** [comment]
Sorry I don't have time recently. Currently I have investigated with the original report owner and confirmed that, the reason for these reports doesn't contain TenantGuid and TenantName is because they will be shown in Syndication partners report page and these information are PII that don't want to show to them.

**Comment by panjkov** [comment]
Ok, could then be good workaround to refactor TenantReport class to support empty values for these two reports, so that we can support Mail reports?





Sent from Windows Mail





From: Toney Sui
Sent: ‎Monday‎, ‎March‎ ‎2‎, ‎2015 ‎2‎:‎46‎ ‎AM
To: Microsoft/o365rwsclient
Cc: Dragan Panjkov





Sorry I don't have time recently. Currently I have investigated with the original report owner and confirmed that, the reason for these reports doesn't contain TenantGuid and TenantName is because they will be shown in Syndication partners report page and these information are PII that don't want to show to them.

**Comment by toneysui** [comment]
Hi Dragan,

I think the code change would be:

1.	Create a new base class “ProtectedTenantReportObject”
2.	Copy all of the properties from TenantReportObject to ProtectedTenantReportObject except TenantName and TenantGuid
3.	Make TenantReportObject inherit from ProtectedTenantReportObject
4.	Update the LoadFromXml method in TenantReportObject.

**Comment by toneysui** [comment]
Yes, you mentioned the most simple way to do that, is to keep the current base class and just let all partner reports inherit from it. The TenantName and TenantGuid columns will be set to NULL if it cannot find the column in the service return result.

**Comment by panjkov** [comment]
TenantReportObject only loads those two properties. Now that you mentioned that LoadFromXml would return null (overlooked that before) I also think we might be able to keep current base classes anf use them for all mail, partner and scorecard reports.
