### ISSUE TITLE
Create New Base Class for Partner and Scorecard reports

### ISSUE THREAD

**Issue by panjkov** [Microsoft/o365rwsclient#7]
partner and scorecard reports don't have TenantName property, and it's unclear whether they should inherit TenantReportObject class.

**Comment by panjkov** [comment]
Any updates?

**Comment by julienjtpierre** [comment]
No updates @panjkov sorry. Busy doing other things at the moment. I don't know whether @toneysui has the bandwidth to sort this out?

**Comment by toneysui** [comment]
@panjkov Sorry I don't have time to do that recently, could you do that by yourself?

**Comment by panjkov** [comment]
Can we first somehow discuss changes needed to be done in base class and the impact to library code, and afterwards I can do the actual changes.









Sent from Windows Mail





From: Toney Sui
Sent: ‎Monday‎, ‎March‎ ‎2‎, ‎2015 ‎2‎:‎49‎ ‎AM
To: Microsoft/o365rwsclient
Cc: Dragan Panjkov





@panjkov Sorry I don't have time to do that recently, could you do that by yourself?

**Comment by toneysui** [comment]
Hi Dragan,

I think the code change would be:


1.       Create a new base class “ProtectedTenantReportObject”

2.       Copy all of the properties from TenantReportObject to ProtectedTenantReportObject except TenantName and TenantGuid

3.       Make TenantReportObject inherit from ProtectedTenantReportObject

4.       Update the LoadFromXml method in TenantReportObject.

**Comment by panjkov** [comment]
TenantReportObject only loads those two properties. Now that you mentioned that LoadFromXml would return null (overlooked that before) I believe we might be able to keep current base classes anf use them for all mail, partner and scorecard reports.
